### PR TITLE
fix(container-release): image path

### PR DESCRIPTION
**Pull request by eyenx**
Correct owner repository

### CODE REVIEW

**Review by tongpu — APPROVED** [review]
LGTM

**Comment by eyenx** [comment]
Still not good...

**Comment by eyenx** [comment]
I guess we need this @tongpu 

https://docs.github.com/en/free-pro-team@latest/packages/guides/enabling-improved-container-support

**Comment by eyenx** [comment]
```
…/back8sup/src docker push ghcr.io/adfinis-sygroup/back8sup:latest     
The push refers to repository [ghcr.io/adfinis-sygroup/back8sup]
e9202daab784: Preparing
e8cda2d6602f: Preparing
ace0eda3e3be: Preparing
denied: failed_precondition: Improved container support has not been enabled for 'adfinis-sygroup'. Learn more: https://docs.github.com/packages/getting-started-with-github-container-registry/enabling-improved-container-support
```

**Comment by tongpu** [comment]
> I guess we need this @tongpu
> 
> https://docs.github.com/en/free-pro-team@latest/packages/guides/enabling-improved-container-support

I enabled it and now it worked.

**Comment by eyenx** [comment]
Perfect. I'll work on the charts now.

--

Adfinis AG
Antonio Tauro, System Engineer, GPG KeyID: 0x0796132F0077A5F8
Güterstrasse 86 | CH-4053 Basel
Office +41 61 500 31 31 | Direct +41 61 500 31 37
www.adfinis.com



-----Original message-----

**Pull request merged**
