### PR TITLE
add autotagging action

### PR DESCRIPTION
**Pull request by eyenx**

### CODE REVIEW

**Comment by tongpu** [comment]
What's wrong with manually tagging releases?

**Comment by eyenx** [comment]
Will we manually do it or not? How can we check if we are doing it or not? 

--
We are now called Adfinis! More at www.adfinis.com

Adfinis AG
Antonio Tauro, System Engineer, GPG KeyID: 0x0796132F0077A5F8
Güterstrasse 86 | CH-4053 Basel
Office +41 61 500 31 31 | Direct +41 61 500 31 37
www.adfinis.com



-----Original message-----

**Comment by hairmare** [comment]
Can you add a `.czrc` for `git cz`  users like me that default to emojis?
```json
{
  "path": "cz-conventional-changelog"
}
```


> What's wrong with manually tagging releases?

Automate all the things! 

Our Ember devs have been doing this with [`yarn semantic-release`](https://github.com/semantic-release/npm) for a while now, I'm not sure if the python devs are doing it in CI yet (but they use the OG [semantic-release](https://github.com/semantic-release/semantic-release) implementation. I've personally had quite some success using the [go-semantic-release](https://github.com/go-semantic-release/semantic-release) implementation on some private repos. Maybe we should try to standardize on one implementation ;)

I also usually set it up with a personal access token rather than using the provided GH_TOKEN. This way the release can trigger other downstream actions on the new tags.

**Comment by eyenx** [comment]
can you recommend a github action for it?

**Comment by hairmare** [comment]
For the go thing I'm using it's official action like so:
https://github.com/radiorabe/cat-page/blob/500afbeee65e0530e18999a3ae07c9abc660cead/.github/workflows/main.yaml#L37-L47

I'm not sure about python/ember but I did start a thread in the #devs channel on our mattermost to get some more inputs as to if there is interest in standardizing this and maybe some inputs as to which one we would want to focus on using per default.

Given the origin of semantic-commit in the angular community there is an argument to made for the js implementation but I haven't really made up my mind on this yet.

I've also considered having a linter that checks commit messages so they adhere to the format (some of our projects have this). I'm not sure if I like the linter since it forces people to rewrite their git history if they don't use semantic-commits from the get go and these rewrites tend to be a daunting tasks for people w/o years of git experience.

**Pull request merged**
